NumPy, short for Numerical Python, is one of the most important foundational packages for numerical computing in Python.
<br/>

Because NumPy provides an easy-to-use C API, it is straightforward to pass data to external libraries written in a low-level language and also for external libraries to return data to Python as NumPy arrays. <br/>

One of the reasons NumPy is so important for numerical computations in Python is because it is designed for efficiency on large arrays of data.<br/>

NumPy-based algorithms are generally **10 to 100 times faster (or more) than** their pure Python counterparts and use significantly less memory.
<br/>
# 4.1 The NumPy ndarray: A Multidimensional Array Object
One of the key features of NumPy is its N-dimensional array object, or ndarray, which is a fast, flexible container for large datasets in Python.

In [1]:
import numpy as np

In [2]:
#Generate some random data
data = np.random.randn(2, 3)

In [3]:
data

array([[ 0.28160005,  1.54045537,  0.79655511],
       [ 0.51493615,  2.0091735 ,  0.08392031]])

Write some mathematical operations with data:

In [4]:
data * 10

array([[  2.81600045,  15.40455369,   7.96555111],
       [  5.14936149,  20.091735  ,   0.8392031 ]])

In [5]:
data + data

array([[ 0.56320009,  3.08091074,  1.59311022],
       [ 1.0298723 ,  4.018347  ,  0.16784062]])

An ndarray is a generic multidimensional container for homogeneous data; that is, **all of the elements must be the same type.**<br/>

Every array has a shape, a **tuple indicating** the **size** of each dimension, and a **dtype**, an object **describing** the **data type** of the array

In [6]:
data.shape

(2, 3)

In [7]:
data.dtype

dtype('float64')

**Becoming proficient in array-oriented programming and thinking is a key step along the way to becoming a scientific Python guru.**<br/>

## Creating ndarrays

In [2]:
import numpy as np
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)

In [3]:
arr1

array([ 6. ,  7.5,  8. ,  0. ,  1. ])

Nested sequences, like a list of equal-length lists,will be converted into a multidimensional array:

In [4]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)

In [5]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [7]:
arr2.ndim

2

In [8]:
arr2.shape

(2, 4)

In [10]:
arr1.dtype

dtype('float64')

In [11]:
arr2.dtype

dtype('int32')

**zeros** and **ones** create arrays of 0s or 1s, respectively, with a
given length or shape. **empty** creates an array without initializing its values to any particular
value.

In [2]:
import numpy as np
np.zeros(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [4]:
np.ones((3,6))

array([[ 1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.]])

In [6]:
np.empty((2, 3, 2))

array([[[  8.90644599e-312,   3.16202013e-322],
        [  0.00000000e+000,   0.00000000e+000],
        [  0.00000000e+000,   3.59725794e+179]],

       [[  6.75973732e-067,   4.15996784e-061],
        [  2.65380824e-032,   1.11555287e-046],
        [  2.80416858e-032,   2.16655185e+184]]])

It’s **not safe** to assume that np.empty will return an array of all
zeros. In some cases, it may return uninitialized **“garbage”** values.

arange is an array-valued version of the built-in Python range function:

In [8]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

<br/>

## Data Types for ndarrays

data type或者dtype是一个特殊的object，它包含关于data的data

In [9]:
arr1 = np.array([1, 2, 3], dtype = np.float64)

In [10]:
arr2 = np.array([1, 2, 3], dtype = np.int32)

In [11]:
arr1.dtype

dtype('float64')

In [12]:
arr2.dtype

dtype('int32')

**Don’t worry** about memorizing the NumPy dtypes, especially if
you’re a new user. It’s often **only necessary** to care about the general
kind of data you’re dealing with, whether **floating point**, **complex**,
**integer**, **boolean**, **string**, or **general Python object**.

You can explicitly convert or cast an array from one dtype to another using ndarray’s
**astype** method

In [13]:
arrr = np.array([1, 2, 3, 4, 5])

In [15]:
arrr.dtype

dtype('int32')

In [16]:
float_arr = arrr.astype(np.float64)

In [17]:
float_arr.dtype

dtype('float64')

反过来，当从float变成integer呢

In [18]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])

In [19]:
arr

array([  3.7,  -1.2,  -2.6,   0.5,  12.9,  10.1])

In [20]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10])

同理，可将string弄成float

In [21]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)

In [22]:
numeric_strings.astype(float)

array([  1.25,  -9.6 ,  42.  ])

两个不同data type之间的转换

In [23]:
int_array = np.arange(10)

In [24]:
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)

In [25]:
int_array.astype(calibers.dtype)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.])

<br/>

## Arithmetic with NumPy Arrays

Arrays enable you to express batch operations on data
without writing any for loops. NumPy users call this **vectorization.**

简单来说，就是对array本身可以做很多关于它们element的操作，然而这样的操作无论是在processing还是JS里面，都要for loop改变每个element

In [26]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])

In [27]:
arr

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])

In [28]:
arr * arr

array([[  1.,   4.,   9.],
       [ 16.,  25.,  36.]])

In [29]:
arr - arr

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [30]:
1 / arr

array([[ 1.        ,  0.5       ,  0.33333333],
       [ 0.25      ,  0.2       ,  0.16666667]])

In [31]:
arr ** 0.5

array([[ 1.        ,  1.41421356,  1.73205081],
       [ 2.        ,  2.23606798,  2.44948974]])

还可以Boolean！

In [32]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])

In [33]:
arr2

array([[  0.,   4.,   1.],
       [  7.,   2.,  12.]])

In [34]:
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]], dtype=bool)

<br/>
## Basic Indexing and Slicing